# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_FarmView.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_FarmView(object):
    def setupUi(self, FarmView):
        FarmView.setObjectName(_fromUtf8("FarmView"))
        FarmView.resize(1302, 661)
        FarmView.setAnimated(True)
        self.centralwidget = QtGui.QWidget(FarmView)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.statusLabel = QtGui.QLabel(self.centralwidget)
        self.statusLabel.setText(_fromUtf8(""))
        self.statusLabel.setObjectName(_fromUtf8("statusLabel"))
        self.gridLayout.addWidget(self.statusLabel, 1, 0, 1, 1)
        self.horizontalLayout_fetchButton = QtGui.QHBoxLayout()
        self.horizontalLayout_fetchButton.setObjectName(_fromUtf8("horizontalLayout_fetchButton"))
        self.fetchButton = QtGui.QPushButton(self.centralwidget)
        self.fetchButton.setObjectName(_fromUtf8("fetchButton"))
        self.horizontalLayout_fetchButton.addWidget(self.fetchButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_fetchButton.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_fetchButton, 2, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.thisNodeTab = QtGui.QWidget()
        self.thisNodeTab.setObjectName(_fromUtf8("thisNodeTab"))
        self.layoutWidget = QtGui.QWidget(self.thisNodeTab)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 114, 122))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_thisNodeButtons = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_thisNodeButtons.setObjectName(_fromUtf8("verticalLayout_thisNodeButtons"))
        self.onlineThisNodeButton = QtGui.QPushButton(self.layoutWidget)
        self.onlineThisNodeButton.setObjectName(_fromUtf8("onlineThisNodeButton"))
        self.verticalLayout_thisNodeButtons.addWidget(self.onlineThisNodeButton)
        self.offlineThisNodeButton = QtGui.QPushButton(self.layoutWidget)
        self.offlineThisNodeButton.setObjectName(_fromUtf8("offlineThisNodeButton"))
        self.verticalLayout_thisNodeButtons.addWidget(self.offlineThisNodeButton)
        self.getOffThisNodeButton = QtGui.QPushButton(self.layoutWidget)
        self.getOffThisNodeButton.setObjectName(_fromUtf8("getOffThisNodeButton"))
        self.verticalLayout_thisNodeButtons.addWidget(self.getOffThisNodeButton)
        self.layoutWidget1 = QtGui.QWidget(self.thisNodeTab)
        self.layoutWidget1.setGeometry(QtCore.QRect(150, 20, 651, 223))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.formLayout_thisNodeLabels = QtGui.QFormLayout(self.layoutWidget1)
        self.formLayout_thisNodeLabels.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_thisNodeLabels.setObjectName(_fromUtf8("formLayout_thisNodeLabels"))
        self.nodeNameLabelLabel = QtGui.QLabel(self.layoutWidget1)
        self.nodeNameLabelLabel.setObjectName(_fromUtf8("nodeNameLabelLabel"))
        self.formLayout_thisNodeLabels.setWidget(0, QtGui.QFormLayout.LabelRole, self.nodeNameLabelLabel)
        self.nodeNameLabel = QtGui.QLabel(self.layoutWidget1)
        self.nodeNameLabel.setText(_fromUtf8(""))
        self.nodeNameLabel.setObjectName(_fromUtf8("nodeNameLabel"))
        self.formLayout_thisNodeLabels.setWidget(0, QtGui.QFormLayout.FieldRole, self.nodeNameLabel)
        self.nodeStatusLabelLabel = QtGui.QLabel(self.layoutWidget1)
        self.nodeStatusLabelLabel.setObjectName(_fromUtf8("nodeStatusLabelLabel"))
        self.formLayout_thisNodeLabels.setWidget(1, QtGui.QFormLayout.LabelRole, self.nodeStatusLabelLabel)
        self.nodeStatusLabel = QtGui.QLabel(self.layoutWidget1)
        self.nodeStatusLabel.setText(_fromUtf8(""))
        self.nodeStatusLabel.setObjectName(_fromUtf8("nodeStatusLabel"))
        self.formLayout_thisNodeLabels.setWidget(1, QtGui.QFormLayout.FieldRole, self.nodeStatusLabel)
        self.taskIDLabelLabel = QtGui.QLabel(self.layoutWidget1)
        self.taskIDLabelLabel.setObjectName(_fromUtf8("taskIDLabelLabel"))
        self.formLayout_thisNodeLabels.setWidget(2, QtGui.QFormLayout.LabelRole, self.taskIDLabelLabel)
        self.taskIDLabel = QtGui.QLabel(self.layoutWidget1)
        self.taskIDLabel.setText(_fromUtf8(""))
        self.taskIDLabel.setObjectName(_fromUtf8("taskIDLabel"))
        self.formLayout_thisNodeLabels.setWidget(2, QtGui.QFormLayout.FieldRole, self.taskIDLabel)
        self.nodeVersionLabelLabel = QtGui.QLabel(self.layoutWidget1)
        self.nodeVersionLabelLabel.setObjectName(_fromUtf8("nodeVersionLabelLabel"))
        self.formLayout_thisNodeLabels.setWidget(3, QtGui.QFormLayout.LabelRole, self.nodeVersionLabelLabel)
        self.nodeVersionLabel = QtGui.QLabel(self.layoutWidget1)
        self.nodeVersionLabel.setText(_fromUtf8(""))
        self.nodeVersionLabel.setObjectName(_fromUtf8("nodeVersionLabel"))
        self.formLayout_thisNodeLabels.setWidget(3, QtGui.QFormLayout.FieldRole, self.nodeVersionLabel)
        self.restrictToProjectLabel = QtGui.QLabel(self.layoutWidget1)
        self.restrictToProjectLabel.setText(_fromUtf8(""))
        self.restrictToProjectLabel.setObjectName(_fromUtf8("restrictToProjectLabel"))
        self.formLayout_thisNodeLabels.setWidget(4, QtGui.QFormLayout.FieldRole, self.restrictToProjectLabel)
        self.minPriorityLabel = QtGui.QLabel(self.layoutWidget1)
        self.minPriorityLabel.setText(_fromUtf8(""))
        self.minPriorityLabel.setObjectName(_fromUtf8("minPriorityLabel"))
        self.formLayout_thisNodeLabels.setWidget(5, QtGui.QFormLayout.FieldRole, self.minPriorityLabel)
        self.capabilitiesLabel = QtGui.QLabel(self.layoutWidget1)
        self.capabilitiesLabel.setText(_fromUtf8(""))
        self.capabilitiesLabel.setObjectName(_fromUtf8("capabilitiesLabel"))
        self.formLayout_thisNodeLabels.setWidget(6, QtGui.QFormLayout.FieldRole, self.capabilitiesLabel)
        self.nodeVersionLabelLabel_4 = QtGui.QLabel(self.layoutWidget1)
        self.nodeVersionLabelLabel_4.setObjectName(_fromUtf8("nodeVersionLabelLabel_4"))
        self.formLayout_thisNodeLabels.setWidget(4, QtGui.QFormLayout.LabelRole, self.nodeVersionLabelLabel_4)
        self.nodeVersionLabelLabel_3 = QtGui.QLabel(self.layoutWidget1)
        self.nodeVersionLabelLabel_3.setObjectName(_fromUtf8("nodeVersionLabelLabel_3"))
        self.formLayout_thisNodeLabels.setWidget(5, QtGui.QFormLayout.LabelRole, self.nodeVersionLabelLabel_3)
        self.frame = QtGui.QFrame(self.thisNodeTab)
        self.frame.setGeometry(QtCore.QRect(1000, 210, 271, 331))
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet(_fromUtf8("border-image: url(:/images/assets/DPS_logo.jpg) 0 0 0 stretch stretch"))
        self.frame.setFrameShape(QtGui.QFrame.Box)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.tabWidget.addTab(self.thisNodeTab, _fromUtf8(""))
        self.renderNodesTab = QtGui.QWidget()
        self.renderNodesTab.setObjectName(_fromUtf8("renderNodesTab"))
        self.gridLayout_6 = QtGui.QGridLayout(self.renderNodesTab)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.horizontalLayout_onOffButtons = QtGui.QHBoxLayout()
        self.horizontalLayout_onOffButtons.setObjectName(_fromUtf8("horizontalLayout_onOffButtons"))
        self.onlineRenderNodesButton = QtGui.QPushButton(self.renderNodesTab)
        self.onlineRenderNodesButton.setObjectName(_fromUtf8("onlineRenderNodesButton"))
        self.horizontalLayout_onOffButtons.addWidget(self.onlineRenderNodesButton)
        self.offlineRenderNodesButton = QtGui.QPushButton(self.renderNodesTab)
        self.offlineRenderNodesButton.setObjectName(_fromUtf8("offlineRenderNodesButton"))
        self.horizontalLayout_onOffButtons.addWidget(self.offlineRenderNodesButton)
        self.getOffRenderNodesButton = QtGui.QPushButton(self.renderNodesTab)
        self.getOffRenderNodesButton.setObjectName(_fromUtf8("getOffRenderNodesButton"))
        self.horizontalLayout_onOffButtons.addWidget(self.getOffRenderNodesButton)
        self.gridLayout_6.addLayout(self.horizontalLayout_onOffButtons, 1, 0, 1, 1)
        self.renderNodeTable = QtGui.QTableWidget(self.renderNodesTab)
        self.renderNodeTable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.renderNodeTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.renderNodeTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.renderNodeTable.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerItem)
        self.renderNodeTable.setCornerButtonEnabled(False)
        self.renderNodeTable.setObjectName(_fromUtf8("renderNodeTable"))
        self.renderNodeTable.setColumnCount(10)
        self.renderNodeTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Wingdings"))
        item.setFont(font)
        self.renderNodeTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.renderNodeTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.renderNodeTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.renderNodeTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.renderNodeTable.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.renderNodeTable.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.renderNodeTable.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.renderNodeTable.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.renderNodeTable.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.renderNodeTable.setHorizontalHeaderItem(9, item)
        self.renderNodeTable.horizontalHeader().setStretchLastSection(True)
        self.renderNodeTable.verticalHeader().setVisible(False)
        self.gridLayout_6.addWidget(self.renderNodeTable, 0, 0, 1, 1)
        self.tabWidget.addTab(self.renderNodesTab, _fromUtf8(""))
        self.jobListTab = QtGui.QWidget()
        self.jobListTab.setObjectName(_fromUtf8("jobListTab"))
        self.gridLayout_11 = QtGui.QGridLayout(self.jobListTab)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.splitter_jobList = QtGui.QSplitter(self.jobListTab)
        self.splitter_jobList.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_jobList.sizePolicy().hasHeightForWidth())
        self.splitter_jobList.setSizePolicy(sizePolicy)
        self.splitter_jobList.setBaseSize(QtCore.QSize(0, 0))
        self.splitter_jobList.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_jobList.setOpaqueResize(True)
        self.splitter_jobList.setHandleWidth(5)
        self.splitter_jobList.setChildrenCollapsible(True)
        self.splitter_jobList.setObjectName(_fromUtf8("splitter_jobList"))
        self.layoutWidget_2 = QtGui.QWidget(self.splitter_jobList)
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.gridLayout_jobListJobs = QtGui.QGridLayout(self.layoutWidget_2)
        self.gridLayout_jobListJobs.setHorizontalSpacing(6)
        self.gridLayout_jobListJobs.setObjectName(_fromUtf8("gridLayout_jobListJobs"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_jobListJobs.addItem(spacerItem1, 0, 1, 1, 4)
        self.jobTableLabel = QtGui.QLabel(self.layoutWidget_2)
        self.jobTableLabel.setObjectName(_fromUtf8("jobTableLabel"))
        self.gridLayout_jobListJobs.addWidget(self.jobTableLabel, 0, 0, 1, 1)
        self.jobTable = QtGui.QTableWidget(self.layoutWidget_2)
        self.jobTable.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.jobTable.setAutoFillBackground(False)
        self.jobTable.setFrameShape(QtGui.QFrame.StyledPanel)
        self.jobTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.jobTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.jobTable.setShowGrid(True)
        self.jobTable.setCornerButtonEnabled(False)
        self.jobTable.setColumnCount(4)
        self.jobTable.setObjectName(_fromUtf8("jobTable"))
        self.jobTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.jobTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.jobTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.jobTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.jobTable.setHorizontalHeaderItem(3, item)
        self.jobTable.horizontalHeader().setStretchLastSection(True)
        self.jobTable.verticalHeader().setVisible(False)
        self.gridLayout_jobListJobs.addWidget(self.jobTable, 1, 0, 1, 5)
        self.groupBox_jobOptions = QtGui.QGroupBox(self.layoutWidget_2)
        self.groupBox_jobOptions.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_jobOptions.setObjectName(_fromUtf8("groupBox_jobOptions"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_jobOptions)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.pauseJobButton = QtGui.QPushButton(self.groupBox_jobOptions)
        self.pauseJobButton.setObjectName(_fromUtf8("pauseJobButton"))
        self.gridLayout_7.addWidget(self.pauseJobButton, 1, 1, 1, 1)
        self.haltJobButton = QtGui.QPushButton(self.groupBox_jobOptions)
        self.haltJobButton.setStyleSheet(_fromUtf8(""))
        self.haltJobButton.setCheckable(False)
        self.haltJobButton.setAutoDefault(False)
        self.haltJobButton.setDefault(False)
        self.haltJobButton.setObjectName(_fromUtf8("haltJobButton"))
        self.gridLayout_7.addWidget(self.haltJobButton, 1, 2, 1, 1)
        self.startJobButton = QtGui.QPushButton(self.groupBox_jobOptions)
        self.startJobButton.setEnabled(True)
        self.startJobButton.setAcceptDrops(False)
        self.startJobButton.setAutoFillBackground(False)
        self.startJobButton.setStyleSheet(_fromUtf8(""))
        self.startJobButton.setCheckable(False)
        self.startJobButton.setFlat(False)
        self.startJobButton.setObjectName(_fromUtf8("startJobButton"))
        self.gridLayout_7.addWidget(self.startJobButton, 1, 0, 1, 1)
        self.killJobButton = QtGui.QPushButton(self.groupBox_jobOptions)
        self.killJobButton.setObjectName(_fromUtf8("killJobButton"))
        self.gridLayout_7.addWidget(self.killJobButton, 2, 0, 1, 1)
        self.resurrectJobButton = QtGui.QPushButton(self.groupBox_jobOptions)
        self.resurrectJobButton.setObjectName(_fromUtf8("resurrectJobButton"))
        self.gridLayout_7.addWidget(self.resurrectJobButton, 2, 1, 1, 1)
        self.refreshButton = QtGui.QPushButton(self.groupBox_jobOptions)
        self.refreshButton.setObjectName(_fromUtf8("refreshButton"))
        self.gridLayout_7.addWidget(self.refreshButton, 2, 2, 1, 1)
        self.gridLayout_jobListJobs.addWidget(self.groupBox_jobOptions, 2, 0, 1, 4)
        self.groupBox_priorityOptions = QtGui.QGroupBox(self.layoutWidget_2)
        self.groupBox_priorityOptions.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBox_priorityOptions.setObjectName(_fromUtf8("groupBox_priorityOptions"))
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox_priorityOptions)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.prioritySetButton = QtGui.QPushButton(self.groupBox_priorityOptions)
        self.prioritySetButton.setObjectName(_fromUtf8("prioritySetButton"))
        self.gridLayout_8.addWidget(self.prioritySetButton, 1, 1, 1, 1)
        self.prioritySpinBox = QtGui.QSpinBox(self.groupBox_priorityOptions)
        self.prioritySpinBox.setMaximum(999)
        self.prioritySpinBox.setProperty("value", 50)
        self.prioritySpinBox.setObjectName(_fromUtf8("prioritySpinBox"))
        self.gridLayout_8.addWidget(self.prioritySpinBox, 1, 0, 1, 1)
        self.gridLayout_jobListJobs.addWidget(self.groupBox_priorityOptions, 2, 4, 1, 1)
        self.layoutWidget_3 = QtGui.QWidget(self.splitter_jobList)
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.gridLayout_taskList = QtGui.QGridLayout(self.layoutWidget_3)
        self.gridLayout_taskList.setObjectName(_fromUtf8("gridLayout_taskList"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_taskList.addItem(spacerItem2, 0, 2, 1, 1)
        self.taskTableLabel = QtGui.QLabel(self.layoutWidget_3)
        self.taskTableLabel.setObjectName(_fromUtf8("taskTableLabel"))
        self.gridLayout_taskList.addWidget(self.taskTableLabel, 0, 0, 1, 2)
        self.groupBox_search = QtGui.QGroupBox(self.layoutWidget_3)
        self.groupBox_search.setObjectName(_fromUtf8("groupBox_search"))
        self.gridLayout_10 = QtGui.QGridLayout(self.groupBox_search)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.taskIDLineEdit = QtGui.QLineEdit(self.groupBox_search)
        self.taskIDLineEdit.setObjectName(_fromUtf8("taskIDLineEdit"))
        self.gridLayout_10.addWidget(self.taskIDLineEdit, 0, 0, 1, 1)
        self.advancedSearchButton = QtGui.QPushButton(self.groupBox_search)
        self.advancedSearchButton.setObjectName(_fromUtf8("advancedSearchButton"))
        self.gridLayout_10.addWidget(self.advancedSearchButton, 0, 1, 1, 1)
        self.gridLayout_taskList.addWidget(self.groupBox_search, 2, 2, 1, 1)
        self.groupBox_subTaskOptions = QtGui.QGroupBox(self.layoutWidget_3)
        self.groupBox_subTaskOptions.setMinimumSize(QtCore.QSize(0, 28))
        self.groupBox_subTaskOptions.setObjectName(_fromUtf8("groupBox_subTaskOptions"))
        self.gridLayout_9 = QtGui.QGridLayout(self.groupBox_subTaskOptions)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.killTaskButton = QtGui.QPushButton(self.groupBox_subTaskOptions)
        self.killTaskButton.setObjectName(_fromUtf8("killTaskButton"))
        self.gridLayout_9.addWidget(self.killTaskButton, 2, 0, 1, 1)
        self.resurrectTaskButton = QtGui.QPushButton(self.groupBox_subTaskOptions)
        self.resurrectTaskButton.setObjectName(_fromUtf8("resurrectTaskButton"))
        self.gridLayout_9.addWidget(self.resurrectTaskButton, 2, 1, 1, 1)
        self.haltTaskButton = QtGui.QPushButton(self.groupBox_subTaskOptions)
        self.haltTaskButton.setObjectName(_fromUtf8("haltTaskButton"))
        self.gridLayout_9.addWidget(self.haltTaskButton, 1, 1, 1, 1)
        self.startTaskButton = QtGui.QPushButton(self.groupBox_subTaskOptions)
        self.startTaskButton.setObjectName(_fromUtf8("startTaskButton"))
        self.gridLayout_9.addWidget(self.startTaskButton, 1, 0, 1, 1)
        self.gridLayout_taskList.addWidget(self.groupBox_subTaskOptions, 2, 0, 1, 2)
        self.phaseTabWidget = QtGui.QTabWidget(self.layoutWidget_3)
        self.phaseTabWidget.setObjectName(_fromUtf8("phaseTabWidget"))
        self.phase01_tab = QtGui.QWidget()
        self.phase01_tab.setObjectName(_fromUtf8("phase01_tab"))
        self.gridLayout_3 = QtGui.QGridLayout(self.phase01_tab)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.phase01_progBar = QtGui.QProgressBar(self.phase01_tab)
        self.phase01_progBar.setProperty("value", 24)
        self.phase01_progBar.setTextVisible(True)
        self.phase01_progBar.setOrientation(QtCore.Qt.Horizontal)
        self.phase01_progBar.setTextDirection(QtGui.QProgressBar.TopToBottom)
        self.phase01_progBar.setObjectName(_fromUtf8("phase01_progBar"))
        self.gridLayout_3.addWidget(self.phase01_progBar, 1, 0, 1, 1)
        self.phase01_taskTable = QtGui.QTableWidget(self.phase01_tab)
        self.phase01_taskTable.setEnabled(True)
        self.phase01_taskTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.phase01_taskTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.phase01_taskTable.setGridStyle(QtCore.Qt.SolidLine)
        self.phase01_taskTable.setCornerButtonEnabled(False)
        self.phase01_taskTable.setObjectName(_fromUtf8("phase01_taskTable"))
        self.phase01_taskTable.setColumnCount(8)
        self.phase01_taskTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.phase01_taskTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.phase01_taskTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.phase01_taskTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.phase01_taskTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.phase01_taskTable.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.phase01_taskTable.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.phase01_taskTable.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.phase01_taskTable.setHorizontalHeaderItem(7, item)
        self.phase01_taskTable.verticalHeader().setVisible(False)
        self.gridLayout_3.addWidget(self.phase01_taskTable, 0, 0, 1, 1)
        self.phaseTabWidget.addTab(self.phase01_tab, _fromUtf8(""))
        self.phase02_tab = QtGui.QWidget()
        self.phase02_tab.setObjectName(_fromUtf8("phase02_tab"))
        self.gridLayout_4 = QtGui.QGridLayout(self.phase02_tab)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.phase02_taskTable = QtGui.QTableWidget(self.phase02_tab)
        self.phase02_taskTable.setEnabled(True)
        self.phase02_taskTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.phase02_taskTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.phase02_taskTable.setGridStyle(QtCore.Qt.SolidLine)
        self.phase02_taskTable.setCornerButtonEnabled(False)
        self.phase02_taskTable.setObjectName(_fromUtf8("phase02_taskTable"))
        self.phase02_taskTable.setColumnCount(8)
        self.phase02_taskTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.phase02_taskTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.phase02_taskTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.phase02_taskTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.phase02_taskTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.phase02_taskTable.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.phase02_taskTable.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.phase02_taskTable.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.phase02_taskTable.setHorizontalHeaderItem(7, item)
        self.phase02_taskTable.verticalHeader().setVisible(False)
        self.gridLayout_4.addWidget(self.phase02_taskTable, 0, 0, 1, 1)
        self.phase02_progBar = QtGui.QProgressBar(self.phase02_tab)
        self.phase02_progBar.setAcceptDrops(False)
        self.phase02_progBar.setProperty("value", 24)
        self.phase02_progBar.setInvertedAppearance(False)
        self.phase02_progBar.setObjectName(_fromUtf8("phase02_progBar"))
        self.gridLayout_4.addWidget(self.phase02_progBar, 1, 0, 1, 1)
        self.phaseTabWidget.addTab(self.phase02_tab, _fromUtf8(""))
        self.phase03_tab = QtGui.QWidget()
        self.phase03_tab.setObjectName(_fromUtf8("phase03_tab"))
        self.gridLayout_12 = QtGui.QGridLayout(self.phase03_tab)
        self.gridLayout_12.setMargin(0)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.phase03_taskTable = QtGui.QTableWidget(self.phase03_tab)
        self.phase03_taskTable.setEnabled(True)
        self.phase03_taskTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.phase03_taskTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.phase03_taskTable.setGridStyle(QtCore.Qt.SolidLine)
        self.phase03_taskTable.setCornerButtonEnabled(False)
        self.phase03_taskTable.setObjectName(_fromUtf8("phase03_taskTable"))
        self.phase03_taskTable.setColumnCount(8)
        self.phase03_taskTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.phase03_taskTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.phase03_taskTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.phase03_taskTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.phase03_taskTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.phase03_taskTable.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.phase03_taskTable.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.phase03_taskTable.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.phase03_taskTable.setHorizontalHeaderItem(7, item)
        self.phase03_taskTable.verticalHeader().setVisible(False)
        self.gridLayout_12.addWidget(self.phase03_taskTable, 0, 0, 1, 1)
        self.phase03_progBar = QtGui.QProgressBar(self.phase03_tab)
        self.phase03_progBar.setProperty("value", 24)
        self.phase03_progBar.setObjectName(_fromUtf8("phase03_progBar"))
        self.gridLayout_12.addWidget(self.phase03_progBar, 1, 0, 1, 1)
        self.phaseTabWidget.addTab(self.phase03_tab, _fromUtf8(""))
        self.phase04_tab = QtGui.QWidget()
        self.phase04_tab.setObjectName(_fromUtf8("phase04_tab"))
        self.gridLayout_13 = QtGui.QGridLayout(self.phase04_tab)
        self.gridLayout_13.setMargin(0)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.phase04_taskTable = QtGui.QTableWidget(self.phase04_tab)
        self.phase04_taskTable.setEnabled(True)
        self.phase04_taskTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.phase04_taskTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.phase04_taskTable.setGridStyle(QtCore.Qt.SolidLine)
        self.phase04_taskTable.setCornerButtonEnabled(False)
        self.phase04_taskTable.setObjectName(_fromUtf8("phase04_taskTable"))
        self.phase04_taskTable.setColumnCount(8)
        self.phase04_taskTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.phase04_taskTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.phase04_taskTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.phase04_taskTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.phase04_taskTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.phase04_taskTable.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.phase04_taskTable.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.phase04_taskTable.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.phase04_taskTable.setHorizontalHeaderItem(7, item)
        self.phase04_taskTable.verticalHeader().setVisible(False)
        self.gridLayout_13.addWidget(self.phase04_taskTable, 0, 0, 1, 1)
        self.phase04_progBar = QtGui.QProgressBar(self.phase04_tab)
        self.phase04_progBar.setProperty("value", 24)
        self.phase04_progBar.setObjectName(_fromUtf8("phase04_progBar"))
        self.gridLayout_13.addWidget(self.phase04_progBar, 1, 0, 1, 1)
        self.phaseTabWidget.addTab(self.phase04_tab, _fromUtf8(""))
        self.gridLayout_taskList.addWidget(self.phaseTabWidget, 1, 0, 1, 3)
        self.gridLayout_11.addWidget(self.splitter_jobList, 0, 0, 1, 1)
        self.tabWidget.addTab(self.jobListTab, _fromUtf8(""))
        self.jobsTab = QtGui.QWidget()
        self.jobsTab.setObjectName(_fromUtf8("jobsTab"))
        self.gridLayout_5 = QtGui.QGridLayout(self.jobsTab)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.scrollArea_recentTasks = QtGui.QScrollArea(self.jobsTab)
        self.scrollArea_recentTasks.setWidgetResizable(True)
        self.scrollArea_recentTasks.setObjectName(_fromUtf8("scrollArea_recentTasks"))
        self.scrollAreaWidgetContents_recentTasks = QtGui.QWidget()
        self.scrollAreaWidgetContents_recentTasks.setGeometry(QtCore.QRect(0, 0, 1258, 527))
        self.scrollAreaWidgetContents_recentTasks.setObjectName(_fromUtf8("scrollAreaWidgetContents_recentTasks"))
        self.gridLayout_2 = QtGui.QGridLayout(self.scrollAreaWidgetContents_recentTasks)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.limitSpinBox = QtGui.QSpinBox(self.scrollAreaWidgetContents_recentTasks)
        self.limitSpinBox.setMaximum(999)
        self.limitSpinBox.setProperty("value", 100)
        self.limitSpinBox.setObjectName(_fromUtf8("limitSpinBox"))
        self.gridLayout_2.addWidget(self.limitSpinBox, 0, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 2, 0, 1, 1)
        self.taskGrid = QtGui.QGridLayout()
        self.taskGrid.setObjectName(_fromUtf8("taskGrid"))
        self.gridLayout_2.addLayout(self.taskGrid, 1, 0, 1, 1)
        self.scrollArea_recentTasks.setWidget(self.scrollAreaWidgetContents_recentTasks)
        self.gridLayout_5.addWidget(self.scrollArea_recentTasks, 0, 0, 1, 1)
        self.tabWidget.addTab(self.jobsTab, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        FarmView.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(FarmView)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        FarmView.setStatusBar(self.statusbar)

        self.retranslateUi(FarmView)
        self.tabWidget.setCurrentIndex(0)
        self.phaseTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(FarmView)

    def retranslateUi(self, FarmView):
        FarmView.setWindowTitle(_translate("FarmView", "FarmView", None))
        self.fetchButton.setText(_translate("FarmView", "Fetch", None))
        self.onlineThisNodeButton.setToolTip(_translate("FarmView", "<html><head/><body><p>Allow this node to accept render tasks</p></body></html>", None))
        self.onlineThisNodeButton.setText(_translate("FarmView", "Online", None))
        self.offlineThisNodeButton.setToolTip(_translate("FarmView", "<html><head/><body><p>Don\'t allow this node to accept any new jobs (it will still finish what it\'s working on)</p></body></html>", None))
        self.offlineThisNodeButton.setText(_translate("FarmView", "Offline", None))
        self.getOffThisNodeButton.setToolTip(_translate("FarmView", "<html><head/><body><p>Tell this node to stop the current job, put it back on the job board, and don\'t accept any more.</p></body></html>", None))
        self.getOffThisNodeButton.setText(_translate("FarmView", "Get Off!", None))
        self.nodeNameLabelLabel.setText(_translate("FarmView", "Node name:", None))
        self.nodeStatusLabelLabel.setText(_translate("FarmView", "Node status:", None))
        self.taskIDLabelLabel.setText(_translate("FarmView", "Task ID:", None))
        self.nodeVersionLabelLabel.setText(_translate("FarmView", "Version:", None))
        self.nodeVersionLabelLabel_4.setText(_translate("FarmView", "Min Priority:", None))
        self.nodeVersionLabelLabel_3.setText(_translate("FarmView", "Capabilities:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.thisNodeTab), _translate("FarmView", "This Node", None))
        self.onlineRenderNodesButton.setText(_translate("FarmView", "Online", None))
        self.offlineRenderNodesButton.setText(_translate("FarmView", "Offline", None))
        self.getOffRenderNodesButton.setText(_translate("FarmView", "Get Off!", None))
        self.renderNodeTable.setSortingEnabled(True)
        item = self.renderNodeTable.horizontalHeaderItem(0)
        item.setText(_translate("FarmView", "þ", None))
        item = self.renderNodeTable.horizontalHeaderItem(1)
        item.setText(_translate("FarmView", "Host", None))
        item = self.renderNodeTable.horizontalHeaderItem(2)
        item.setText(_translate("FarmView", "Status", None))
        item = self.renderNodeTable.horizontalHeaderItem(3)
        item.setText(_translate("FarmView", "Task ID", None))
        item = self.renderNodeTable.horizontalHeaderItem(4)
        item.setText(_translate("FarmView", "Project", None))
        item = self.renderNodeTable.horizontalHeaderItem(5)
        item.setText(_translate("FarmView", "Restrict to Project", None))
        item = self.renderNodeTable.horizontalHeaderItem(6)
        item.setText(_translate("FarmView", "Min Priority", None))
        item = self.renderNodeTable.horizontalHeaderItem(7)
        item.setText(_translate("FarmView", "Capabilities", None))
        item = self.renderNodeTable.horizontalHeaderItem(8)
        item.setText(_translate("FarmView", "Version", None))
        item = self.renderNodeTable.horizontalHeaderItem(9)
        item.setText(_translate("FarmView", "Last heartbeat", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.renderNodesTab), _translate("FarmView", "Render Nodes", None))
        self.jobTableLabel.setText(_translate("FarmView", "Job List", None))
        self.jobTable.setSortingEnabled(True)
        item = self.jobTable.horizontalHeaderItem(0)
        item.setText(_translate("FarmView", "Job ID", None))
        item = self.jobTable.horizontalHeaderItem(1)
        item.setText(_translate("FarmView", "Priority", None))
        item = self.jobTable.horizontalHeaderItem(2)
        item.setText(_translate("FarmView", "Owner", None))
        item = self.jobTable.horizontalHeaderItem(3)
        item.setText(_translate("FarmView", "Job Name", None))
        self.groupBox_jobOptions.setTitle(_translate("FarmView", "Job Options", None))
        self.pauseJobButton.setText(_translate("FarmView", "Pause", None))
        self.haltJobButton.setText(_translate("FarmView", "Halt", None))
        self.startJobButton.setText(_translate("FarmView", "Start", None))
        self.killJobButton.setText(_translate("FarmView", "Kill", None))
        self.resurrectJobButton.setText(_translate("FarmView", "Resurrect", None))
        self.refreshButton.setText(_translate("FarmView", "Refresh", None))
        self.groupBox_priorityOptions.setTitle(_translate("FarmView", "Change Priority", None))
        self.prioritySetButton.setText(_translate("FarmView", "Set", None))
        self.taskTableLabel.setText(_translate("FarmView", "Task List (job: none selected)", None))
        self.groupBox_search.setTitle(_translate("FarmView", "Search", None))
        self.taskIDLineEdit.setPlaceholderText(_translate("FarmView", "Type TaskID, press Enter", None))
        self.advancedSearchButton.setText(_translate("FarmView", "Advanced...", None))
        self.groupBox_subTaskOptions.setTitle(_translate("FarmView", "Subtask Options", None))
        self.killTaskButton.setText(_translate("FarmView", "Kill", None))
        self.resurrectTaskButton.setText(_translate("FarmView", "Resurrect", None))
        self.haltTaskButton.setText(_translate("FarmView", "Halt", None))
        self.startTaskButton.setText(_translate("FarmView", "Start", None))
        self.phase01_taskTable.setSortingEnabled(True)
        item = self.phase01_taskTable.horizontalHeaderItem(0)
        item.setText(_translate("FarmView", "Task ID", None))
        item = self.phase01_taskTable.horizontalHeaderItem(1)
        item.setText(_translate("FarmView", "Priority", None))
        item = self.phase01_taskTable.horizontalHeaderItem(2)
        item.setText(_translate("FarmView", "Host", None))
        item = self.phase01_taskTable.horizontalHeaderItem(3)
        item.setText(_translate("FarmView", "Status", None))
        item = self.phase01_taskTable.horizontalHeaderItem(4)
        item.setText(_translate("FarmView", "Start Time", None))
        item = self.phase01_taskTable.horizontalHeaderItem(5)
        item.setText(_translate("FarmView", "End Time", None))
        item = self.phase01_taskTable.horizontalHeaderItem(6)
        item.setText(_translate("FarmView", "Duration", None))
        item = self.phase01_taskTable.horizontalHeaderItem(7)
        item.setText(_translate("FarmView", "Code", None))
        self.phaseTabWidget.setTabText(self.phaseTabWidget.indexOf(self.phase01_tab), _translate("FarmView", "Phase 01", None))
        self.phase02_taskTable.setSortingEnabled(True)
        item = self.phase02_taskTable.horizontalHeaderItem(0)
        item.setText(_translate("FarmView", "Task ID", None))
        item = self.phase02_taskTable.horizontalHeaderItem(1)
        item.setText(_translate("FarmView", "Priority", None))
        item = self.phase02_taskTable.horizontalHeaderItem(2)
        item.setText(_translate("FarmView", "Host", None))
        item = self.phase02_taskTable.horizontalHeaderItem(3)
        item.setText(_translate("FarmView", "Status", None))
        item = self.phase02_taskTable.horizontalHeaderItem(4)
        item.setText(_translate("FarmView", "Start Time", None))
        item = self.phase02_taskTable.horizontalHeaderItem(5)
        item.setText(_translate("FarmView", "End Time", None))
        item = self.phase02_taskTable.horizontalHeaderItem(6)
        item.setText(_translate("FarmView", "Duration", None))
        item = self.phase02_taskTable.horizontalHeaderItem(7)
        item.setText(_translate("FarmView", "Code", None))
        self.phaseTabWidget.setTabText(self.phaseTabWidget.indexOf(self.phase02_tab), _translate("FarmView", "Phase 02", None))
        self.phase03_taskTable.setSortingEnabled(True)
        item = self.phase03_taskTable.horizontalHeaderItem(0)
        item.setText(_translate("FarmView", "Task ID", None))
        item = self.phase03_taskTable.horizontalHeaderItem(1)
        item.setText(_translate("FarmView", "Priority", None))
        item = self.phase03_taskTable.horizontalHeaderItem(2)
        item.setText(_translate("FarmView", "Host", None))
        item = self.phase03_taskTable.horizontalHeaderItem(3)
        item.setText(_translate("FarmView", "Status", None))
        item = self.phase03_taskTable.horizontalHeaderItem(4)
        item.setText(_translate("FarmView", "Start Time", None))
        item = self.phase03_taskTable.horizontalHeaderItem(5)
        item.setText(_translate("FarmView", "End Time", None))
        item = self.phase03_taskTable.horizontalHeaderItem(6)
        item.setText(_translate("FarmView", "Duration", None))
        item = self.phase03_taskTable.horizontalHeaderItem(7)
        item.setText(_translate("FarmView", "Code", None))
        self.phaseTabWidget.setTabText(self.phaseTabWidget.indexOf(self.phase03_tab), _translate("FarmView", "Phase 03", None))
        self.phase04_taskTable.setSortingEnabled(True)
        item = self.phase04_taskTable.horizontalHeaderItem(0)
        item.setText(_translate("FarmView", "Task ID", None))
        item = self.phase04_taskTable.horizontalHeaderItem(1)
        item.setText(_translate("FarmView", "Priority", None))
        item = self.phase04_taskTable.horizontalHeaderItem(2)
        item.setText(_translate("FarmView", "Host", None))
        item = self.phase04_taskTable.horizontalHeaderItem(3)
        item.setText(_translate("FarmView", "Status", None))
        item = self.phase04_taskTable.horizontalHeaderItem(4)
        item.setText(_translate("FarmView", "Start Time", None))
        item = self.phase04_taskTable.horizontalHeaderItem(5)
        item.setText(_translate("FarmView", "End Time", None))
        item = self.phase04_taskTable.horizontalHeaderItem(6)
        item.setText(_translate("FarmView", "Duration", None))
        item = self.phase04_taskTable.horizontalHeaderItem(7)
        item.setText(_translate("FarmView", "Code", None))
        self.phaseTabWidget.setTabText(self.phaseTabWidget.indexOf(self.phase04_tab), _translate("FarmView", "Phase 04", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.jobListTab), _translate("FarmView", "Job List", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.jobsTab), _translate("FarmView", "Recent Tasks", None))

import RS_FarmView_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    FarmView = QtGui.QMainWindow()
    ui = Ui_FarmView()
    ui.setupUi(FarmView)
    FarmView.show()
    sys.exit(app.exec_())

