# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_Submitter.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(411, 444)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.sceneLabel = QtGui.QLabel(self.centralwidget)
        self.sceneLabel.setObjectName(_fromUtf8("sceneLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.sceneLabel)
        self.sceneLayout = QtGui.QGridLayout()
        self.sceneLayout.setObjectName(_fromUtf8("sceneLayout"))
        self.sceneButton = QtGui.QPushButton(self.centralwidget)
        self.sceneButton.setObjectName(_fromUtf8("sceneButton"))
        self.sceneLayout.addWidget(self.sceneButton, 0, 1, 1, 1)
        self.sceneLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.sceneLineEdit.setObjectName(_fromUtf8("sceneLineEdit"))
        self.sceneLayout.addWidget(self.sceneLineEdit, 0, 0, 1, 1)
        self.formLayout.setLayout(0, QtGui.QFormLayout.FieldRole, self.sceneLayout)
        self.projLabel = QtGui.QLabel(self.centralwidget)
        self.projLabel.setObjectName(_fromUtf8("projLabel"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.projLabel)
        self.projLayout = QtGui.QGridLayout()
        self.projLayout.setObjectName(_fromUtf8("projLayout"))
        self.projButton = QtGui.QPushButton(self.centralwidget)
        self.projButton.setObjectName(_fromUtf8("projButton"))
        self.projLayout.addWidget(self.projButton, 0, 1, 1, 1)
        self.projLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.projLineEdit.setReadOnly(True)
        self.projLineEdit.setObjectName(_fromUtf8("projLineEdit"))
        self.projLayout.addWidget(self.projLineEdit, 0, 0, 1, 1)
        self.formLayout.setLayout(1, QtGui.QFormLayout.FieldRole, self.projLayout)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setObjectName(_fromUtf8("line"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.SpanningRole, self.line)
        self.niceNameLabel = QtGui.QLabel(self.centralwidget)
        self.niceNameLabel.setObjectName(_fromUtf8("niceNameLabel"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.niceNameLabel)
        self.niceNameLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.niceNameLineEdit.setText(_fromUtf8(""))
        self.niceNameLineEdit.setObjectName(_fromUtf8("niceNameLineEdit"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.niceNameLineEdit)
        self.renderLayersLabel = QtGui.QLabel(self.centralwidget)
        self.renderLayersLabel.setObjectName(_fromUtf8("renderLayersLabel"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.renderLayersLabel)
        self.renderLayersLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.renderLayersLineEdit.setObjectName(_fromUtf8("renderLayersLineEdit"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.renderLayersLineEdit)
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setLineWidth(2)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.SpanningRole, self.line_2)
        self.startFrameLabel = QtGui.QLabel(self.centralwidget)
        self.startFrameLabel.setObjectName(_fromUtf8("startFrameLabel"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.startFrameLabel)
        self.startSpinBox = QtGui.QSpinBox(self.centralwidget)
        self.startSpinBox.setAccelerated(True)
        self.startSpinBox.setMinimum(1)
        self.startSpinBox.setMaximum(99999)
        self.startSpinBox.setObjectName(_fromUtf8("startSpinBox"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.startSpinBox)
        self.endFrameLabel = QtGui.QLabel(self.centralwidget)
        self.endFrameLabel.setObjectName(_fromUtf8("endFrameLabel"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.endFrameLabel)
        self.endSpinBox = QtGui.QSpinBox(self.centralwidget)
        self.endSpinBox.setAccelerated(True)
        self.endSpinBox.setMinimum(1)
        self.endSpinBox.setMaximum(99999)
        self.endSpinBox.setObjectName(_fromUtf8("endSpinBox"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.endSpinBox)
        self.priorityLabel = QtGui.QLabel(self.centralwidget)
        self.priorityLabel.setObjectName(_fromUtf8("priorityLabel"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.priorityLabel)
        self.prioritySpinBox = QtGui.QSpinBox(self.centralwidget)
        self.prioritySpinBox.setMinimum(-100)
        self.prioritySpinBox.setMaximum(99999)
        self.prioritySpinBox.setProperty("value", 50)
        self.prioritySpinBox.setObjectName(_fromUtf8("prioritySpinBox"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.prioritySpinBox)
        self.executableLabel = QtGui.QLabel(self.centralwidget)
        self.executableLabel.setObjectName(_fromUtf8("executableLabel"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.LabelRole, self.executableLabel)
        self.executableComboBox = QtGui.QComboBox(self.centralwidget)
        self.executableComboBox.setObjectName(_fromUtf8("executableComboBox"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.FieldRole, self.executableComboBox)
        self.cmdLabel = QtGui.QLabel(self.centralwidget)
        self.cmdLabel.setObjectName(_fromUtf8("cmdLabel"))
        self.formLayout.setWidget(10, QtGui.QFormLayout.LabelRole, self.cmdLabel)
        self.cmdLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.cmdLineEdit.setText(_fromUtf8(""))
        self.cmdLineEdit.setObjectName(_fromUtf8("cmdLineEdit"))
        self.formLayout.setWidget(10, QtGui.QFormLayout.FieldRole, self.cmdLineEdit)
        self.phasesLabel = QtGui.QLabel(self.centralwidget)
        self.phasesLabel.setObjectName(_fromUtf8("phasesLabel"))
        self.formLayout.setWidget(11, QtGui.QFormLayout.LabelRole, self.phasesLabel)
        self.phaseLayout = QtGui.QHBoxLayout()
        self.phaseLayout.setObjectName(_fromUtf8("phaseLayout"))
        self.testCheckBox = QtGui.QCheckBox(self.centralwidget)
        self.testCheckBox.setChecked(True)
        self.testCheckBox.setObjectName(_fromUtf8("testCheckBox"))
        self.phaseLayout.addWidget(self.testCheckBox)
        self.finalCheckBox = QtGui.QCheckBox(self.centralwidget)
        self.finalCheckBox.setChecked(True)
        self.finalCheckBox.setObjectName(_fromUtf8("finalCheckBox"))
        self.phaseLayout.addWidget(self.finalCheckBox)
        self.autocompCheckBox = QtGui.QCheckBox(self.centralwidget)
        self.autocompCheckBox.setEnabled(False)
        self.autocompCheckBox.setObjectName(_fromUtf8("autocompCheckBox"))
        self.phaseLayout.addWidget(self.autocompCheckBox)
        self.formLayout.setLayout(11, QtGui.QFormLayout.FieldRole, self.phaseLayout)
        self.testFramesLabel = QtGui.QLabel(self.centralwidget)
        self.testFramesLabel.setObjectName(_fromUtf8("testFramesLabel"))
        self.formLayout.setWidget(12, QtGui.QFormLayout.LabelRole, self.testFramesLabel)
        self.testFramesSpinBox = QtGui.QSpinBox(self.centralwidget)
        self.testFramesSpinBox.setMinimum(1)
        self.testFramesSpinBox.setMaximum(999)
        self.testFramesSpinBox.setProperty("value", 10)
        self.testFramesSpinBox.setObjectName(_fromUtf8("testFramesSpinBox"))
        self.formLayout.setWidget(12, QtGui.QFormLayout.FieldRole, self.testFramesSpinBox)
        self.testNodesLabel = QtGui.QLabel(self.centralwidget)
        self.testNodesLabel.setObjectName(_fromUtf8("testNodesLabel"))
        self.formLayout.setWidget(13, QtGui.QFormLayout.LabelRole, self.testNodesLabel)
        self.testNodesSpinBox = QtGui.QSpinBox(self.centralwidget)
        self.testNodesSpinBox.setEnabled(True)
        self.testNodesSpinBox.setProperty("value", 1)
        self.testNodesSpinBox.setObjectName(_fromUtf8("testNodesSpinBox"))
        self.formLayout.setWidget(13, QtGui.QFormLayout.FieldRole, self.testNodesSpinBox)
        self.specialJobsLabel = QtGui.QLabel(self.centralwidget)
        self.specialJobsLabel.setObjectName(_fromUtf8("specialJobsLabel"))
        self.formLayout.setWidget(14, QtGui.QFormLayout.LabelRole, self.specialJobsLabel)
        self.specialLayout = QtGui.QHBoxLayout()
        self.specialLayout.setObjectName(_fromUtf8("specialLayout"))
        self.legoLayersCheckBox = QtGui.QCheckBox(self.centralwidget)
        self.legoLayersCheckBox.setEnabled(False)
        self.legoLayersCheckBox.setObjectName(_fromUtf8("legoLayersCheckBox"))
        self.specialLayout.addWidget(self.legoLayersCheckBox)
        self.formLayout.setLayout(14, QtGui.QFormLayout.FieldRole, self.specialLayout)
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setLineWidth(2)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.formLayout.setWidget(15, QtGui.QFormLayout.SpanningRole, self.line_3)
        self.requirementsLabel = QtGui.QLabel(self.centralwidget)
        self.requirementsLabel.setObjectName(_fromUtf8("requirementsLabel"))
        self.formLayout.setWidget(16, QtGui.QFormLayout.LabelRole, self.requirementsLabel)
        self.reqsGrid = QtGui.QGridLayout()
        self.reqsGrid.setObjectName(_fromUtf8("reqsGrid"))
        self.formLayout.setLayout(16, QtGui.QFormLayout.FieldRole, self.reqsGrid)
        self.line_4 = QtGui.QFrame(self.centralwidget)
        self.line_4.setLineWidth(2)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.formLayout.setWidget(17, QtGui.QFormLayout.SpanningRole, self.line_4)
        self.verticalLayout.addLayout(self.formLayout)
        self.submitButton = QtGui.QPushButton(self.centralwidget)
        self.submitButton.setObjectName(_fromUtf8("submitButton"))
        self.verticalLayout.addWidget(self.submitButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.startFrameLabel.setBuddy(self.startSpinBox)
        self.endFrameLabel.setBuddy(self.endSpinBox)
        self.priorityLabel.setBuddy(self.prioritySpinBox)
        self.testFramesLabel.setBuddy(self.testFramesSpinBox)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.startSpinBox, self.endSpinBox)
        MainWindow.setTabOrder(self.endSpinBox, self.prioritySpinBox)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Submitter", None))
        self.sceneLabel.setText(_translate("MainWindow", "Scene:", None))
        self.sceneButton.setText(_translate("MainWindow", "Browse", None))
        self.sceneLineEdit.setPlaceholderText(_translate("MainWindow", "Scene File", None))
        self.projLabel.setText(_translate("MainWindow", "Maya Proj:", None))
        self.projButton.setText(_translate("MainWindow", "Browse", None))
        self.projLineEdit.setPlaceholderText(_translate("MainWindow", "Project Directory", None))
        self.niceNameLabel.setText(_translate("MainWindow", "Job Name:", None))
        self.niceNameLineEdit.setPlaceholderText(_translate("MainWindow", "Nice Name for the Job", None))
        self.renderLayersLabel.setText(_translate("MainWindow", "Render Layers:", None))
        self.renderLayersLineEdit.setPlaceholderText(_translate("MainWindow", "Render,Layers,Seperated,With,Commas", None))
        self.startFrameLabel.setText(_translate("MainWindow", "Start Frame:", None))
        self.endFrameLabel.setText(_translate("MainWindow", "End Frame:", None))
        self.priorityLabel.setText(_translate("MainWindow", "Priority:", None))
        self.executableLabel.setText(_translate("MainWindow", "Executable:", None))
        self.cmdLabel.setText(_translate("MainWindow", "CMD:", None))
        self.cmdLineEdit.setPlaceholderText(_translate("MainWindow", "Anything entered here will be included in the CMD", None))
        self.phasesLabel.setText(_translate("MainWindow", "Phases:", None))
        self.testCheckBox.setText(_translate("MainWindow", "Test Phase", None))
        self.finalCheckBox.setText(_translate("MainWindow", "Final Phase", None))
        self.autocompCheckBox.setText(_translate("MainWindow", "Auto Comp", None))
        self.testFramesLabel.setText(_translate("MainWindow", "<html><head/><body><p>Test By Frame:</p></body></html>", None))
        self.testNodesLabel.setText(_translate("MainWindow", "Test Nodes:", None))
        self.specialJobsLabel.setText(_translate("MainWindow", "Special Jobs:", None))
        self.legoLayersCheckBox.setText(_translate("MainWindow", "Lego Layers", None))
        self.requirementsLabel.setText(_translate("MainWindow", "Requirements:", None))
        self.submitButton.setText(_translate("MainWindow", "Submit", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

