RenderNodeError_String = "This node was either not found in the database or has is_render_node set to 0! If you wish to render on this node it must be registered with the database and be enabled as a render node. To register, run register.exe or register.py. To enable as a render node, edit the node in FarmView and enable rendering on it."
GetOff_String = "<B>WARNING</B>: All progress on current tasks will be lost for the selected render nodes. Are you sure you want to stop these nodes?\n"
MultiNodeEdit_String = "Are you sure you want to edit multiple nodes? A box will open for each node checked."
GetOffLocal_String = "All progress on the current job will be lost. Are you sure you want to stop it?"
DoesNotExist_Str = "Information about this node cannot be displayed because it is not registered on the render farm. You may continue to use Farm View, but it must be restarted after this node is registered if you wish to see this node's information."
