# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_RenderNodeMain.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_RenderNodeMainWindow(object):
    def setupUi(self, RenderNodeMainWindow):
        RenderNodeMainWindow.setObjectName(_fromUtf8("RenderNodeMainWindow"))
        RenderNodeMainWindow.resize(793, 748)
        self.centralwidget = QtGui.QWidget(RenderNodeMainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.formLayout = QtGui.QFormLayout(self.centralwidget)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.MainGroup = QtGui.QTabWidget(self.centralwidget)
        self.MainGroup.setIconSize(QtCore.QSize(0, 0))
        self.MainGroup.setUsesScrollButtons(False)
        self.MainGroup.setObjectName(_fromUtf8("MainGroup"))
        self.RenderNodeMainTab = QtGui.QWidget()
        self.RenderNodeMainTab.setObjectName(_fromUtf8("RenderNodeMainTab"))
        self.formLayout_2 = QtGui.QFormLayout(self.RenderNodeMainTab)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.trayButton = QtGui.QPushButton(self.RenderNodeMainTab)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(True)
        self.trayButton.setFont(font)
        self.trayButton.setObjectName(_fromUtf8("trayButton"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.SpanningRole, self.trayButton)
        self.formLayout_thisNodeLabels = QtGui.QFormLayout()
        self.formLayout_thisNodeLabels.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_thisNodeLabels.setObjectName(_fromUtf8("formLayout_thisNodeLabels"))
        self.nodeNameLabel_LABEL = QtGui.QLabel(self.RenderNodeMainTab)
        self.nodeNameLabel_LABEL.setObjectName(_fromUtf8("nodeNameLabel_LABEL"))
        self.formLayout_thisNodeLabels.setWidget(0, QtGui.QFormLayout.LabelRole, self.nodeNameLabel_LABEL)
        self.nodeNameLabel = QtGui.QLabel(self.RenderNodeMainTab)
        self.nodeNameLabel.setObjectName(_fromUtf8("nodeNameLabel"))
        self.formLayout_thisNodeLabels.setWidget(0, QtGui.QFormLayout.FieldRole, self.nodeNameLabel)
        self.nodeStatusLabel_LABEL = QtGui.QLabel(self.RenderNodeMainTab)
        self.nodeStatusLabel_LABEL.setObjectName(_fromUtf8("nodeStatusLabel_LABEL"))
        self.formLayout_thisNodeLabels.setWidget(1, QtGui.QFormLayout.LabelRole, self.nodeStatusLabel_LABEL)
        self.nodeStatusLabel = QtGui.QLabel(self.RenderNodeMainTab)
        self.nodeStatusLabel.setObjectName(_fromUtf8("nodeStatusLabel"))
        self.formLayout_thisNodeLabels.setWidget(1, QtGui.QFormLayout.FieldRole, self.nodeStatusLabel)
        self.taskIDLabelLabel = QtGui.QLabel(self.RenderNodeMainTab)
        self.taskIDLabelLabel.setObjectName(_fromUtf8("taskIDLabelLabel"))
        self.formLayout_thisNodeLabels.setWidget(2, QtGui.QFormLayout.LabelRole, self.taskIDLabelLabel)
        self.taskIDLabel = QtGui.QLabel(self.RenderNodeMainTab)
        self.taskIDLabel.setObjectName(_fromUtf8("taskIDLabel"))
        self.formLayout_thisNodeLabels.setWidget(2, QtGui.QFormLayout.FieldRole, self.taskIDLabel)
        self.nodeVersionLabel_LABEL = QtGui.QLabel(self.RenderNodeMainTab)
        self.nodeVersionLabel_LABEL.setObjectName(_fromUtf8("nodeVersionLabel_LABEL"))
        self.formLayout_thisNodeLabels.setWidget(3, QtGui.QFormLayout.LabelRole, self.nodeVersionLabel_LABEL)
        self.nodeVersionLabel = QtGui.QLabel(self.RenderNodeMainTab)
        self.nodeVersionLabel.setObjectName(_fromUtf8("nodeVersionLabel"))
        self.formLayout_thisNodeLabels.setWidget(3, QtGui.QFormLayout.FieldRole, self.nodeVersionLabel)
        self.minPriorityLabel_LABEL = QtGui.QLabel(self.RenderNodeMainTab)
        self.minPriorityLabel_LABEL.setObjectName(_fromUtf8("minPriorityLabel_LABEL"))
        self.formLayout_thisNodeLabels.setWidget(4, QtGui.QFormLayout.LabelRole, self.minPriorityLabel_LABEL)
        self.minPriorityLabel = QtGui.QLabel(self.RenderNodeMainTab)
        self.minPriorityLabel.setObjectName(_fromUtf8("minPriorityLabel"))
        self.formLayout_thisNodeLabels.setWidget(4, QtGui.QFormLayout.FieldRole, self.minPriorityLabel)
        self.capabilitiesLabel_LABEL = QtGui.QLabel(self.RenderNodeMainTab)
        self.capabilitiesLabel_LABEL.setObjectName(_fromUtf8("capabilitiesLabel_LABEL"))
        self.formLayout_thisNodeLabels.setWidget(5, QtGui.QFormLayout.LabelRole, self.capabilitiesLabel_LABEL)
        self.capabilitiesLabel = QtGui.QLabel(self.RenderNodeMainTab)
        self.capabilitiesLabel.setObjectName(_fromUtf8("capabilitiesLabel"))
        self.formLayout_thisNodeLabels.setWidget(5, QtGui.QFormLayout.FieldRole, self.capabilitiesLabel)
        self.weekSchedule_LABEL = QtGui.QLabel(self.RenderNodeMainTab)
        self.weekSchedule_LABEL.setObjectName(_fromUtf8("weekSchedule_LABEL"))
        self.formLayout_thisNodeLabels.setWidget(6, QtGui.QFormLayout.LabelRole, self.weekSchedule_LABEL)
        self.scheduleEnabled = QtGui.QLabel(self.RenderNodeMainTab)
        self.scheduleEnabled.setObjectName(_fromUtf8("scheduleEnabled"))
        self.formLayout_thisNodeLabels.setWidget(6, QtGui.QFormLayout.FieldRole, self.scheduleEnabled)
        self.pulseLabel_LABEL = QtGui.QLabel(self.RenderNodeMainTab)
        self.pulseLabel_LABEL.setObjectName(_fromUtf8("pulseLabel_LABEL"))
        self.formLayout_thisNodeLabels.setWidget(7, QtGui.QFormLayout.LabelRole, self.pulseLabel_LABEL)
        self.pulseLabel = QtGui.QLabel(self.RenderNodeMainTab)
        self.pulseLabel.setObjectName(_fromUtf8("pulseLabel"))
        self.formLayout_thisNodeLabels.setWidget(7, QtGui.QFormLayout.FieldRole, self.pulseLabel)
        self.formLayout_2.setLayout(1, QtGui.QFormLayout.SpanningRole, self.formLayout_thisNodeLabels)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.refreshButton = QtGui.QPushButton(self.RenderNodeMainTab)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../Images/refresh.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refreshButton.setIcon(icon)
        self.refreshButton.setCheckable(False)
        self.refreshButton.setObjectName(_fromUtf8("refreshButton"))
        self.horizontalLayout_6.addWidget(self.refreshButton)
        self.editThisNodeButton = QtGui.QPushButton(self.RenderNodeMainTab)
        self.editThisNodeButton.setEnabled(True)
        self.editThisNodeButton.setObjectName(_fromUtf8("editThisNodeButton"))
        self.horizontalLayout_6.addWidget(self.editThisNodeButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.autoUpdateCheckBox = QtGui.QCheckBox(self.RenderNodeMainTab)
        self.autoUpdateCheckBox.setEnabled(True)
        self.autoUpdateCheckBox.setChecked(True)
        self.autoUpdateCheckBox.setObjectName(_fromUtf8("autoUpdateCheckBox"))
        self.horizontalLayout_6.addWidget(self.autoUpdateCheckBox)
        self.formLayout_2.setLayout(2, QtGui.QFormLayout.SpanningRole, self.horizontalLayout_6)
        self.buttonLayout = QtGui.QHBoxLayout()
        self.buttonLayout.setObjectName(_fromUtf8("buttonLayout"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.buttonLayout.addItem(spacerItem1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.buttonLayout.addItem(spacerItem2)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.buttonLayout.addItem(spacerItem3)
        self.onlineButton = QtGui.QPushButton(self.RenderNodeMainTab)
        self.onlineButton.setMinimumSize(QtCore.QSize(96, 0))
        self.onlineButton.setObjectName(_fromUtf8("onlineButton"))
        self.buttonLayout.addWidget(self.onlineButton)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.buttonLayout.addItem(spacerItem4)
        self.offlineButton = QtGui.QPushButton(self.RenderNodeMainTab)
        self.offlineButton.setMinimumSize(QtCore.QSize(96, 0))
        self.offlineButton.setObjectName(_fromUtf8("offlineButton"))
        self.buttonLayout.addWidget(self.offlineButton)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.buttonLayout.addItem(spacerItem5)
        self.getoffButton = QtGui.QPushButton(self.RenderNodeMainTab)
        self.getoffButton.setMinimumSize(QtCore.QSize(96, 0))
        self.getoffButton.setObjectName(_fromUtf8("getoffButton"))
        self.buttonLayout.addWidget(self.getoffButton)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.buttonLayout.addItem(spacerItem6)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.buttonLayout.addItem(spacerItem7)
        self.clearButton = QtGui.QToolButton(self.RenderNodeMainTab)
        self.clearButton.setCheckable(False)
        self.clearButton.setPopupMode(QtGui.QToolButton.DelayedPopup)
        self.clearButton.setAutoRaise(False)
        self.clearButton.setObjectName(_fromUtf8("clearButton"))
        self.buttonLayout.addWidget(self.clearButton)
        self.formLayout_2.setLayout(3, QtGui.QFormLayout.SpanningRole, self.buttonLayout)
        self.outputTabWidget = QtGui.QTabWidget(self.RenderNodeMainTab)
        self.outputTabWidget.setObjectName(_fromUtf8("outputTabWidget"))
        self.outputTab = QtGui.QWidget()
        self.outputTab.setObjectName(_fromUtf8("outputTab"))
        self.formLayout_3 = QtGui.QFormLayout(self.outputTab)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.outputTextEdit = QtGui.QTextEdit(self.outputTab)
        self.outputTextEdit.setMinimumSize(QtCore.QSize(0, 350))
        self.outputTextEdit.setFrameShape(QtGui.QFrame.NoFrame)
        self.outputTextEdit.setLineWidth(0)
        self.outputTextEdit.setReadOnly(True)
        self.outputTextEdit.setObjectName(_fromUtf8("outputTextEdit"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.SpanningRole, self.outputTextEdit)
        self.outputTextEdit.raise_()
        self.outputTextEdit.raise_()
        self.outputTabWidget.addTab(self.outputTab, _fromUtf8(""))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.outputTabWidget)
        self.MainGroup.addTab(self.RenderNodeMainTab, _fromUtf8(""))
        self.formLayout.setWidget(0, QtGui.QFormLayout.SpanningRole, self.MainGroup)
        self.statusLayout = QtGui.QHBoxLayout()
        self.statusLayout.setObjectName(_fromUtf8("statusLayout"))
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.statusLayout.addItem(spacerItem8)
        self.renderServerPixmap = QtGui.QLabel(self.centralwidget)
        self.renderServerPixmap.setText(_fromUtf8(""))
        self.renderServerPixmap.setPixmap(QtGui.QPixmap(_fromUtf8("../Images/status/notStarted.png")))
        self.renderServerPixmap.setObjectName(_fromUtf8("renderServerPixmap"))
        self.statusLayout.addWidget(self.renderServerPixmap)
        self.renderServerLabel = QtGui.QLabel(self.centralwidget)
        self.renderServerLabel.setObjectName(_fromUtf8("renderServerLabel"))
        self.statusLayout.addWidget(self.renderServerLabel)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.statusLayout.addItem(spacerItem9)
        self.scheduleThreadPixmap = QtGui.QLabel(self.centralwidget)
        self.scheduleThreadPixmap.setText(_fromUtf8(""))
        self.scheduleThreadPixmap.setPixmap(QtGui.QPixmap(_fromUtf8("../Images/status/notStarted.png")))
        self.scheduleThreadPixmap.setObjectName(_fromUtf8("scheduleThreadPixmap"))
        self.statusLayout.addWidget(self.scheduleThreadPixmap)
        self.scheduleThreadLabel = QtGui.QLabel(self.centralwidget)
        self.scheduleThreadLabel.setObjectName(_fromUtf8("scheduleThreadLabel"))
        self.statusLayout.addWidget(self.scheduleThreadLabel)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.statusLayout.addItem(spacerItem10)
        self.pulseThreadPixmap = QtGui.QLabel(self.centralwidget)
        self.pulseThreadPixmap.setText(_fromUtf8(""))
        self.pulseThreadPixmap.setPixmap(QtGui.QPixmap(_fromUtf8("../Images/status/notStarted.png")))
        self.pulseThreadPixmap.setObjectName(_fromUtf8("pulseThreadPixmap"))
        self.statusLayout.addWidget(self.pulseThreadPixmap)
        self.pulseThreadLabel = QtGui.QLabel(self.centralwidget)
        self.pulseThreadLabel.setObjectName(_fromUtf8("pulseThreadLabel"))
        self.statusLayout.addWidget(self.pulseThreadLabel)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.statusLayout.addItem(spacerItem11)
        self.formLayout.setLayout(2, QtGui.QFormLayout.SpanningRole, self.statusLayout)
        RenderNodeMainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(RenderNodeMainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        RenderNodeMainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(RenderNodeMainWindow)
        QtCore.QMetaObject.connectSlotsByName(RenderNodeMainWindow)

    def retranslateUi(self, RenderNodeMainWindow):
        RenderNodeMainWindow.setWindowTitle(_translate("RenderNodeMainWindow", "RenderNodeMain", None))
        self.trayButton.setText(_translate("RenderNodeMainWindow", "Send To Tray", None))
        self.nodeNameLabel_LABEL.setText(_translate("RenderNodeMainWindow", "Node name:", None))
        self.nodeNameLabel.setText(_translate("RenderNodeMainWindow", "N/A", None))
        self.nodeStatusLabel_LABEL.setText(_translate("RenderNodeMainWindow", "Node status:", None))
        self.nodeStatusLabel.setText(_translate("RenderNodeMainWindow", "N/A", None))
        self.taskIDLabelLabel.setText(_translate("RenderNodeMainWindow", "Task ID:", None))
        self.taskIDLabel.setText(_translate("RenderNodeMainWindow", "N/A", None))
        self.nodeVersionLabel_LABEL.setText(_translate("RenderNodeMainWindow", "Version:", None))
        self.nodeVersionLabel.setText(_translate("RenderNodeMainWindow", "N/A", None))
        self.minPriorityLabel_LABEL.setText(_translate("RenderNodeMainWindow", "Min Priority:", None))
        self.minPriorityLabel.setText(_translate("RenderNodeMainWindow", "N/A", None))
        self.capabilitiesLabel_LABEL.setText(_translate("RenderNodeMainWindow", "Capabilities:", None))
        self.capabilitiesLabel.setText(_translate("RenderNodeMainWindow", "N/A", None))
        self.weekSchedule_LABEL.setText(_translate("RenderNodeMainWindow", "Schedule Enabled:", None))
        self.scheduleEnabled.setText(_translate("RenderNodeMainWindow", "N/A", None))
        self.pulseLabel_LABEL.setText(_translate("RenderNodeMainWindow", "Pulse:", None))
        self.pulseLabel.setText(_translate("RenderNodeMainWindow", "N/A", None))
        self.refreshButton.setText(_translate("RenderNodeMainWindow", "Refresh", None))
        self.editThisNodeButton.setText(_translate("RenderNodeMainWindow", "Edit This Node...", None))
        self.autoUpdateCheckBox.setText(_translate("RenderNodeMainWindow", "Auto Update", None))
        self.onlineButton.setText(_translate("RenderNodeMainWindow", "Online", None))
        self.offlineButton.setText(_translate("RenderNodeMainWindow", "Offline", None))
        self.getoffButton.setText(_translate("RenderNodeMainWindow", "Get Off!", None))
        self.clearButton.setText(_translate("RenderNodeMainWindow", "Clear", None))
        self.outputTabWidget.setTabText(self.outputTabWidget.indexOf(self.outputTab), _translate("RenderNodeMainWindow", "Output", None))
        self.MainGroup.setTabText(self.MainGroup.indexOf(self.RenderNodeMainTab), _translate("RenderNodeMainWindow", "RenderNodeMain", None))
        self.renderServerLabel.setText(_translate("RenderNodeMainWindow", "Render Server", None))
        self.scheduleThreadLabel.setText(_translate("RenderNodeMainWindow", "Schedule Thread", None))
        self.pulseThreadLabel.setText(_translate("RenderNodeMainWindow", "Pulse Thread", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    RenderNodeMainWindow = QtGui.QMainWindow()
    ui = Ui_RenderNodeMainWindow()
    ui.setupUi(RenderNodeMainWindow)
    RenderNodeMainWindow.show()
    sys.exit(app.exec_())

