global proc DPSHydra_TaskUpdate(){
  int $currentFrame = `currentTime -q`;
  string $currentRenderLayer = `editRenderLayerGlobals -q -currentRenderLayer`;
  print ("[Hydra] UpdateData: " + $currentFrame + " " + $currentRenderLayer);
  print "[Hydra] Sending UpdateData to RenderManager...";
  //TODO:Fix Temp Path
  system(("start python C:\\Users\\David\\Documents\\GitHub\\DPS_Hydra\\TaskUpdater.py TaskProgress " + $currentFrame + " " + $currentRenderLayer));
  print "[Hydra] UpdateData Sent!";
}
